name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Build with the default Java
    steps:
    - uses: actions/checkout@v2
    - name: Show Java version
      run: java -version
    - name: Build with Maven
      run: mvn -f com.examples.myproject/pom.xml clean verify

