# This workflow will build a Java project with Maven
name: Java CI with Maven for PR

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test against several OSes:
        os: [macos-latest, windows-latest]

    name: Build with Java 17 on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn verify
      working-directory: com.examples.myproject

